---
name: checkov

on: push

jobs:
  check-ov:
    name: check-ov
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      actions: none
      checks: none
      deployments: none
      id-token: none
      issues: none
      discussions: none
      pages: none
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: write

    steps:
      - name: install
        run: |
          pip install -q -U urllib3 requests
          pip install -q checkov
      - name: checkout code
        uses: actions/checkout@v4
      - name: scan
        run: |
          echo $GITHUB_WORKSPACE
          checkov --config-file $GITHUB_WORKSPACE/.github/workflows/super-linter.yml --directory $GITHUB_WORKSPACE
