---
name: Super-Linter
on: push
permissions: read-all

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    permissions:
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Run Super-Linter
        uses: super-linter/super-linter@v6.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: echo some details
        run: |
            "echo" "$GITHUB_WORKSPACE"
            cd $GITHUB_WORKSPACE
            ls -ltr