---
name: Super-Linter
on: push
permissions: { }

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    permissions:
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Run Super-Linter
        uses: super-linter/super-linter@v6.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: echo some details
        run: |
          "echo" GITHUB_WORKSPACE is: "$GITHUB_WORKSPACE"
          "cd" /
          "echo" The current directory is: "$PWD"

          "cd" "$GITHUB_WORKSPACE"
          "cd" ../../..
          "echo" The current directory is: "$PWD"

          "cd" "$GITHUB_WORKSPACE"
          "echo" The current directory is: "$PWD"

          "echo" List of files:
          "ls" -ltr

          "echo" Contents of index.html:
          "cat" index.html

      - name: deploying ...
        run: |
          "cd" /var/www/html
          "sudo" rm -f index.html
          "sudo" rm -f index.nginx-debian.html
          "sudo" cp "$GITHUB_WORKSPACE"/README.md .
          "sudo" cp "$GITHUB_WORKSPACE"/LICENSE .
          "sudo" cp "$GITHUB_WORKSPACE"/index.html .

      - name: starting ...
        run: |
          "sudo" systemctl start nginx.service

      - name: connecting via ssh ...
        uses: lhotari/action-upterm@v1
